// Página inicial do site

import React from 'react'
import './home.scss'
import { AcUnit } from '@material-ui/icons' // Importação de uma logo
import Navbar from '../components/navbar/Navbar'

const Home = () => {
  return (
    <div className='home'>
       <Navbar></Navbar>   
       <img
        width="100%"
        src='https://images.pexels.com/photos/6899260/pexels-photo-6899260.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500' alt=''></img>
       Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sed ipsum aliquam, blandit libero vel, accumsan lectus. In scelerisque, elit in tincidunt vestibulum, quam dolor rutrum justo, aliquam pellentesque lacus lectus sed nunc. Fusce lorem nulla, sodales nec mauris dictum, porta faucibus ex. In hac habitasse platea dictumst. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras et dui ut ex rhoncus elementum sit amet sit amet orci. Morbi placerat, ligula vel consectetur facilisis, lacus risus rutrum tellus, ut commodo neque erat nec ante. Aenean scelerisque mollis ex, nec cursus massa tempor a. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse semper ex a risus pulvinar, at ultricies justo placerat. Aliquam erat volutpat.

Morbi quis fringilla felis, id finibus purus. Aenean ultrices turpis ac dui cursus, quis lacinia libero tempor. Sed velit lorem, interdum non luctus aliquet, dignissim ut neque. Ut luctus quam augue, ut varius purus vestibulum vel. Mauris aliquam tellus sed felis viverra consectetur. Aenean tristique mauris eget justo gravida pretium. Nullam scelerisque scelerisque odio eu venenatis. Nullam mauris ex, suscipit et justo et, posuere egestas nisl. Fusce lacinia, dolor nec pretium convallis, purus neque lacinia mi, sit amet vulputate libero velit sit amet ligula. Praesent in augue dignissim, finibus ante quis, rhoncus dui. Mauris et malesuada ligula. Curabitur vulputate faucibus ex, vel malesuada urna vestibulum malesuada. Vivamus ornare nulla id dui vehicula, non lobortis turpis convallis. Suspendisse luctus nisl et urna iaculis commodo. Vestibulum posuere eleifend ex, varius porttitor ligula sodales nec. Suspendisse pellentesque sapien quam, nec pellentesque sapien bibendum a.

Curabitur ultricies tincidunt est sit amet feugiat. Suspendisse mollis tempor risus ac pellentesque. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum pharetra mollis justo vel pretium. Integer sapien libero, bibendum sed consectetur vitae, viverra id neque. Nam a leo nibh. Vivamus quis euismod mauris, quis tempus lectus. Etiam placerat eget nulla id fermentum. Suspendisse tempor in ex et vestibulum. Donec rhoncus ipsum metus, id varius lacus bibendum eu. Sed eu vehicula massa. In a metus orci. Sed urna eros, ullamcorper eu gravida eget, scelerisque id dui.

Proin venenatis viverra ex, eget euismod sem auctor eu. Pellentesque eleifend, orci sit amet accumsan commodo, dui justo suscipit nisl, vel posuere libero mauris vitae lectus. Nulla justo est, porttitor nec velit gravida, scelerisque fermentum eros. Etiam sit amet auctor urna. Etiam a felis ex. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Phasellus tristique finibus lorem, eget luctus erat efficitur ac.

Suspendisse potenti. Nunc scelerisque, ex id venenatis aliquet, neque diam ultrices justo, vitae condimentum leo mauris ac ex. Maecenas id ante at nunc mattis iaculis. Maecenas in enim vel purus ultrices vehicula id sed elit. Aliquam eu ligula id ante tincidunt faucibus vitae at tortor. Quisque rhoncus, dolor eu imperdiet bibendum, elit ipsum semper sem, id vulputate augue mauris ut ligula. Cras tristique odio non magna eleifend, sit amet pretium magna bibendum. Sed ac aliquam orci. Quisque sit amet velit lacinia, maximus nisi eget, imperdiet lorem. Cras rutrum lacinia maximus. Etiam pellentesque tellus eget risus sagittis pellentesque. Duis dignissim interdum orci, non convallis diam fringilla eget. Vestibulum vitae consequat ante.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sed ipsum aliquam, blandit libero vel, accumsan lectus. In scelerisque, elit in tincidunt vestibulum, quam dolor rutrum justo, aliquam pellentesque lacus lectus sed nunc. Fusce lorem nulla, sodales nec mauris dictum, porta faucibus ex. In hac habitasse platea dictumst. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras et dui ut ex rhoncus elementum sit amet sit amet orci. Morbi placerat, ligula vel consectetur facilisis, lacus risus rutrum tellus, ut commodo neque erat nec ante. Aenean scelerisque mollis ex, nec cursus massa tempor a. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse semper ex a risus pulvinar, at ultricies justo placerat. Aliquam erat volutpat.

Morbi quis fringilla felis, id finibus purus. Aenean ultrices turpis ac dui cursus, quis lacinia libero tempor. Sed velit lorem, interdum non luctus aliquet, dignissim ut neque. Ut luctus quam augue, ut varius purus vestibulum vel. Mauris aliquam tellus sed felis viverra consectetur. Aenean tristique mauris eget justo gravida pretium. Nullam scelerisque scelerisque odio eu venenatis. Nullam mauris ex, suscipit et justo et, posuere egestas nisl. Fusce lacinia, dolor nec pretium convallis, purus neque lacinia mi, sit amet vulputate libero velit sit amet ligula. Praesent in augue dignissim, finibus ante quis, rhoncus dui. Mauris et malesuada ligula. Curabitur vulputate faucibus ex, vel malesuada urna vestibulum malesuada. Vivamus ornare nulla id dui vehicula, non lobortis turpis convallis. Suspendisse luctus nisl et urna iaculis commodo. Vestibulum posuere eleifend ex, varius porttitor ligula sodales nec. Suspendisse pellentesque sapien quam, nec pellentesque sapien bibendum a.

Curabitur ultricies tincidunt est sit amet feugiat. Suspendisse mollis tempor risus ac pellentesque. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum pharetra mollis justo vel pretium. Integer sapien libero, bibendum sed consectetur vitae, viverra id neque. Nam a leo nibh. Vivamus quis euismod mauris, quis tempus lectus. Etiam placerat eget nulla id fermentum. Suspendisse tempor in ex et vestibulum. Donec rhoncus ipsum metus, id varius lacus bibendum eu. Sed eu vehicula massa. In a metus orci. Sed urna eros, ullamcorper eu gravida eget, scelerisque id dui.

Proin venenatis viverra ex, eget euismod sem auctor eu. Pellentesque eleifend, orci sit amet accumsan commodo, dui justo suscipit nisl, vel posuere libero mauris vitae lectus. Nulla justo est, porttitor nec velit gravida, scelerisque fermentum eros. Etiam sit amet auctor urna. Etiam a felis ex. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Phasellus tristique finibus lorem, eget luctus erat efficitur ac.

Suspendisse potenti. Nunc scelerisque, ex id venenatis aliquet, neque diam ultrices justo, vitae condimentum leo mauris ac ex. Maecenas id ante at nunc mattis iaculis. Maecenas in enim vel purus ultrices vehicula id sed elit. Aliquam eu ligula id ante tincidunt faucibus vitae at tortor. Quisque rhoncus, dolor eu imperdiet bibendum, elit ipsum semper sem, id vulputate augue mauris ut ligula. Cras tristique odio non magna eleifend, sit amet pretium magna bibendum. Sed ac aliquam orci. Quisque sit amet velit lacinia, maximus nisi eget, imperdiet lorem. Cras rutrum lacinia maximus. Etiam pellentesque tellus eget risus sagittis pellentesque. Duis dignissim interdum orci, non convallis diam fringilla eget. Vestibulum vitae consequat ante.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sed ipsum aliquam, blandit libero vel, accumsan lectus. In scelerisque, elit in tincidunt vestibulum, quam dolor rutrum justo, aliquam pellentesque lacus lectus sed nunc. Fusce lorem nulla, sodales nec mauris dictum, porta faucibus ex. In hac habitasse platea dictumst. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras et dui ut ex rhoncus elementum sit amet sit amet orci. Morbi placerat, ligula vel consectetur facilisis, lacus risus rutrum tellus, ut commodo neque erat nec ante. Aenean scelerisque mollis ex, nec cursus massa tempor a. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse semper ex a risus pulvinar, at ultricies justo placerat. Aliquam erat volutpat.

Morbi quis fringilla felis, id finibus purus. Aenean ultrices turpis ac dui cursus, quis lacinia libero tempor. Sed velit lorem, interdum non luctus aliquet, dignissim ut neque. Ut luctus quam augue, ut varius purus vestibulum vel. Mauris aliquam tellus sed felis viverra consectetur. Aenean tristique mauris eget justo gravida pretium. Nullam scelerisque scelerisque odio eu venenatis. Nullam mauris ex, suscipit et justo et, posuere egestas nisl. Fusce lacinia, dolor nec pretium convallis, purus neque lacinia mi, sit amet vulputate libero velit sit amet ligula. Praesent in augue dignissim, finibus ante quis, rhoncus dui. Mauris et malesuada ligula. Curabitur vulputate faucibus ex, vel malesuada urna vestibulum malesuada. Vivamus ornare nulla id dui vehicula, non lobortis turpis convallis. Suspendisse luctus nisl et urna iaculis commodo. Vestibulum posuere eleifend ex, varius porttitor ligula sodales nec. Suspendisse pellentesque sapien quam, nec pellentesque sapien bibendum a.

Curabitur ultricies tincidunt est sit amet feugiat. Suspendisse mollis tempor risus ac pellentesque. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum pharetra mollis justo vel pretium. Integer sapien libero, bibendum sed consectetur vitae, viverra id neque. Nam a leo nibh. Vivamus quis euismod mauris, quis tempus lectus. Etiam placerat eget nulla id fermentum. Suspendisse tempor in ex et vestibulum. Donec rhoncus ipsum metus, id varius lacus bibendum eu. Sed eu vehicula massa. In a metus orci. Sed urna eros, ullamcorper eu gravida eget, scelerisque id dui.

Proin venenatis viverra ex, eget euismod sem auctor eu. Pellentesque eleifend, orci sit amet accumsan commodo, dui justo suscipit nisl, vel posuere libero mauris vitae lectus. Nulla justo est, porttitor nec velit gravida, scelerisque fermentum eros. Etiam sit amet auctor urna. Etiam a felis ex. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Phasellus tristique finibus lorem, eget luctus erat efficitur ac.

Suspendisse potenti. Nunc scelerisque, ex id venenatis aliquet, neque diam ultrices justo, vitae condimentum leo mauris ac ex. Maecenas id ante at nunc mattis iaculis. Maecenas in enim vel purus ultrices vehicula id sed elit. Aliquam eu ligula id ante tincidunt faucibus vitae at tortor. Quisque rhoncus, dolor eu imperdiet bibendum, elit ipsum semper sem, id vulputate augue mauris ut ligula. Cras tristique odio non magna eleifend, sit amet pretium magna bibendum. Sed ac aliquam orci. Quisque sit amet velit lacinia, maximus nisi eget, imperdiet lorem. Cras rutrum lacinia maximus. Etiam pellentesque tellus eget risus sagittis pellentesque. Duis dignissim interdum orci, non convallis diam fringilla eget. Vestibulum vitae consequat ante.
    </div>
  )
}

export default Home
